apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  labels:
    app: myapp
spec:
  selector:
    matchLabels:
      app: myapp
  replicas: 1
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: chaitanya0145/myapp:v1
        ports:
        - name: myapp-port
          containerPort: 8080
      initContainers:
        - name: init-mydb
          image: busybox
          command: ['sh', '-c','until nslookup projectdb; do echo waiting for mydb; sleep 2; done;']
        - name: init-memcache
          image: busybox
          command: ['sh', '-c','until nslookup my-memcached; do echo waiting for memcached; sleep 2; done;']
